POST https://lt-records.local/wp-json/pixelgradelt_records/v1/compositions/refresh
Authorization: Basic R0P5Ca3YYLLREgeXJpo2pw5SVgp0LtwI pixelgradelt_records
Accept: application/json
Content-Type: application/json

{
  "composer": {
	"name": "pixelgradelt\/my-site",
	"type": "project",
	"license": "MIT",
	"description": "A Pixelgrade LT WordPress site.",
	"homepage": "https:\/\/local.local",
	"time": "2021-06-17T10:55:28+00:00",
	"authors": [],
	"keywords": [],
	"support": {
	  "issues": "https:\/\/pixelgradelt.com",
	  "forum": "https:\/\/pixelgradelt.com"
	},
	"repositories": [
	  {
		"type": "composer",
		"url": "https:\/\/lt-records.local\/ltpackagist\/",
		"options": {
		  "ssl": {
			"verify_peer": false
		  }
		}
	  },
	  {
		"type": "composer",
		"url": "https:\/\/repo.packagist.org"
	  }
	],
	"require": {
	  "pixelgradelt-records\/part_another-test": "*, >=3.0.0",
	  "pixelgradelt-records\/part_test-test": "*, ^4.0",
	  "pixelgradelt-records\/part_yet-another": "*"
	},
	"require-dev": {},
	"config": {
	  "optimize-autoloader": true,
	  "preferred-install": "dist"
	},
	"minimum-stability": "stable",
	"prefer-stable": false,
	"extra": {
	  "installer-paths": {
		"web\/app\/mu-plugins\/{$name}\/": [
		  "type:wordpress-muplugin"
		],
		"web\/app\/plugins\/{$name}\/": [
		  "type:wordpress-plugin"
		],
		"web\/app\/themes\/{$name}\/": [
		  "type:wordpress-theme"
		]
	  },
	  "lt-user": "def502001b6268c78749c5d24d6537843f8babe6813d860939e340c8c97ee4ee90cfd4b6fe671226950d15deb01b067a135bee22ed5cd05898ac5c67b77d347644fbdef1216b84e9b38faefa0176b453e9b5265d1339af2fc166eb78d65e8e2c8b12a3250139e12c3002f2180bee7595b3eb493b6d82e4727c9fa398cb2a85289054787abcdf6f20ab664ef5b2f95026d1e161947754",
	  "wordpress-install-dir": "web\/wp",
	  "lt-fingerprint": "2b90bdc18d17a28a2f56f35325536e99"
	},
	"scripts": {
	  "post-root-package-install": [
		"php -r \"copy('.env.example', '.env');\""
	  ],
	  "test": [
		"phpcs"
	  ]
	}
  }
}

###

POST https://lt-records.local/wp-json/pixelgradelt_records/v1/compositions
Authorization: Basic R0P5Ca3YYLLREgeXJpo2pw5SVgp0LtwI pixelgradelt_records
Accept: application/json
Content-Type: application/json

{
  "siteId": "some-site id",
  "userId": 123,
  "orderId": [ 888, 2345, 213, 234 ],
  "requirePackages": [
	{
	  "name": "pixelgradelt-records\/part_yet-another",
	  "version": "*"
	},
	{
	  "name": "pixelgradelt-records\/part_another-test",
	  "version": "*, >=3.0.0"
	},
	{
	  "name": "pixelgradelt-records\/part_test-test",
	  "version": "*, ^4.0"
	}
  ],
  "composer": {
	"name": "pixelgradelt\/my-site",
	"authors": [
	  {
		"name": "Vlad Olaru",
		"email": "vlad@pixelgrade.com",
		"homepage": "https://thinkwritecode.com",
		"role": "Development, infrastructure, and product development"
	  }
	],
	"homepage": "https://local.local",
	"keywords": [],
	"support": {},
	"config": {
	  "optimize-autoloader": false,
	  "preferred-install": "dev"
	},
	"minimum-stability": "stable",
	"prefer-stable": false,
	"extra": {
	  "something": "yet"
	},
	"scripts": {
	  "test2": [
		"phpcs"
	  ]
	}
  }
}

###

POST https://lt-records.local/wp-json/pixelgradelt_records/v1/compositions
Authorization: Basic R0P5Ca3YYLLREgeXJpo2pw5SVgp0LtwI pixelgradelt_records
Accept: application/json
Content-Type: application/json

{
  "siteId": "some-site id",
  "userId": 123,
  "orderId": [ 888, 2345, 213, 234 ],
  "requirePackages": [
	{
	  "name": "pixelgradelt-records\/part_yet-another",
	  "version": "*",
	  "requiredBy": [
		{
		  "name": "pixelgradelt-retailer\/first-solution",
		  "requiredVersion": "*"
		}
	  ]
	},
	{
	  "name": "pixelgradelt-records\/part_another-test",
	  "version": "*, >=3.0.0",
	  "requiredBy": [
		{
		  "name": "pixelgradelt-retailer\/fourth-solution",
		  "requiredVersion": "*"
		},
		{
		  "name": "pixelgradelt-retailer\/second-solution",
		  "requiredVersion": ">=3.0.0"
		}
	  ]
	},
	{
	  "name": "pixelgradelt-records\/part_test-test",
	  "version": "*, ^4.0",
	  "requiredBy": [
		{
		  "name": "pixelgradelt-retailer\/fourth-solution",
		  "requiredVersion": "*"
		},
		{
		  "name": "pixelgradelt-retailer\/second-solution",
		  "requiredVersion": "^4.0"
		}
	  ]
	}
  ],
  "composer": {
	"name": "pixelgradelt\/my-site",
	"authors": [
      {
        "name": "Vlad Olaru",
        "email": "vlad@pixelgrade.com",
        "homepage": "https://thinkwritecode.com",
        "role": "Development, infrastructure, and product development"
      }
	],
	"homepage": "https://local.local",
	"keywords": [],
	"support": {},
	"config": {
	  "optimize-autoloader": false,
	  "preferred-install": "dev"
	},
	"minimum-stability": "stable",
	"prefer-stable": false,
	"extra": {
	  "something": "yet"
	},
	"scripts": {
	  "test2": [
		"phpcs"
	  ]
	}
  }
}

###

POST https://lt-records.local/wp-json/pixelgradelt_records/v1/compositions
Authorization: Basic R0P5Ca3YYLLREgeXJpo2pw5SVgp0LtwI pixelgradelt_records
Accept: application/json
Content-Type: application/json

{
  "siteId": "some-site id",
  "userId": 123,
  "orderId": [ 888, 2345, 213, 234 ],
  "requirePackages": [
	{
	  "name": "pixelgradelt-records\/part_yet-another",
	  "version": "*"
	},
	{
	  "name": "pixelgradelt-records\/part_another-test",
	  "version": "*, >=3.0.0"
	},
	{
	  "name": "pixelgradelt-records\/part_test-test",
	  "version": "*, ^4.0"
	}
  ]
}

###

POST https://lt-records.local/wp-json/pixelgradelt_records/v1/compositions
Authorization: Basic R0P5Ca3YYLLREgeXJpo2pw5SVgp0LtwI pixelgradelt_records
Accept: application/json
Content-Type: application/json

{
  "siteId": "some-site id",
  "userId": 123,
  "orderId": [ 888, 2345, 213, 234 ]
}

###

GET https://lt-records.local/wp-json/pixelgradelt_records/v1/packages
Authorization: Basic R0P5Ca3YYLLREgeXJpo2pw5SVgp0LtwI pixelgradelt_records
Accept: application/json

###

GET https://ltsatispress.local/ltpackagist/packages.json
Accept: application/json
Authorization: Basic R0P5Ca3YYLLREgeXJpo2pw5SVgp0LtwI pixelgradelt_records

###
